name=RapidBootWiFi
version=1.2.3
author=Idlan Zafran Mohd Zaidie
maintainer=Idlan Zafran Mohd Zaidie <lanzaidie@gmail.com>
sentence=Handles 3-rapid-boot WiFi resets, LittleFS boot counting, and WiFiManager setup.
paragraph=A robust, drop-in library for ESP32 and ESP8266 devices that automatically handles WiFi provisioning via a Captive Portal, and provides a physical "Factory Reset" mechanism by power-cycling the device 3 times rapidly. Includes flash-memory parameter auto-saving and non-blocking background reconnects.
category=Communication
url=https://github.com/IdlanZafran/RapidBootWiFi
architectures=esp32,esp8266
depends=WiFiManager
